##############################################################################
# Content
##############################################################################

# 项目页面链接
projects_url: https://github.com/jwzz693

# 页面方向
direction: ltr

# 导航菜单
nav:
  首页: /
  关于: /about/
  文章: /archives/
  分类: /categories/
  标签: /tags/
  项目: https://github.com/jwzz693

# 社交链接
social_links:
  -
    icon: github
    link: https://github.com/jwzz693
  -
    icon: mail
    link: mailto:jwzz693@github.com
  -
    icon: rss
    link: /yuanfang123/atom.xml

# 首页标签云
tags_overview: true

# 首页文章列表
posts_overview:
  show_all_posts: false
  post_count: 10
  sort_updated: false

# 归档
archive:
  sort_updated: false

# 文章页
post:
  show_updated: true

# 版权年份
copyright:
  start_year: 2026
  end_year:

# 404 页面
error_404:
  enabled: true
  title: "404 - 页面走丢了"
  description: "你访问的页面不存在，可能已被删除或链接错误。"


##############################################################################
# Look and Feel
##############################################################################

# Logo 设置
logo:
  enabled: true
  width: 50
  height: 50
  url: /images/logo.png
  gravatar: false
  grayout: true

# Favicon
favicon:
  desktop:
    url: /images/favicon.ico
    gravatar: false
  android:
    url: /images/favicon-192x192.png
    gravatar: false
  apple:
    url: /images/apple-touch-icon.png
    gravatar: false

# 代码高亮配色
# highlight: rainbow

# 颜色方案: 'dark' = 黑客终端风格
colorscheme: dark

# 页面最大宽度 (rem)
page_width: 48


##############################################################################
# Miscellaneous
##############################################################################

# RSS
rss: false

# Open Graph
open_graph:
  fb_app_id:
  fb_admins:
  twitter_id:
  google_plus:


##############################################################################
# Plugins
##############################################################################

# MathJax
mathjax:
  enabled: false

# Disqus 评论
disqus:
  enabled: false
  shortname:

# Utterances 评论
utterances:
  enabled: false

# Google Analytics
google_analytics:
  enabled: false
  id:

# 百度统计
baidu_analytics:
  enabled: false
  id:

# Cloudflare Analytics
cloudflare_analytics:
  enabled: false
  id:

# Umami Analytics
umami_analytics:
  enabled: false
  id:
  host:
  script_name:

# Gravatar
gravatar:
  email:
  hash:

# CDN
cdn:
  enable: true
  jquery: https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js
  clipboard: https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.7/clipboard.min.js
  font_awesome: https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css
  justified_gallery_css: https://cdnjs.cloudflare.com/ajax/libs/justifiedGallery/3.8.1/css/justifiedGallery.min.css
  justified_gallery_js: https://cdnjs.cloudflare.com/ajax/libs/justifiedGallery/3.8.1/js/jquery.justifiedGallery.min.js
